clear screen;

SET SERVEROUTPUT ON

--CREATE OR REPLACE TYPE TBL AS TABLE OF EMPLOYEES%ROWTYPE
--/

CREATE OR REPLACE PROCEDURE PRINT_AVERAGES
IS
  
    TYPE RCRD IS RECORD (
      TOTAL_SALARY NUMBER,
      DEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE
    );

    TYPE tablou_indexat IS TABLE OF RCRD
     INDEX BY BINARY_INTEGER;
     
     SALARIES_TABLE tablou_indexat;

BEGIN
    SELECT SUM(SALARY) AS TOTAL_SALARY, DEPARTMENT_ID
    BULK COLLECT INTO SALARIES_TABLE
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID;


    FOR i IN 1..SALARIES_TABLE.COUNT LOOP
      DBMS_OUTPUT.PUT_LINE(SALARIES_TABLE(i).TOTAL_SALARY ||' ' || SALARIES_TABLE(i).DEPARTMENT_ID);
    END LOOP;

END PRINT_AVERAGES;
/


CREATE OR REPLACE PROCEDURE list_employees(salary_raise IN NUMBER)
IS
BEGIN
  
  DBMS_OUTPUT.PUT_LINE('Averages before update');

  PRINT_AVERAGES();
  
  UPDATE EMPLOYEES E
  SET SALARY = SALARY + salary_raise
  WHERE E.SALARY < (SELECT AVG(SALARY) 
                    FROM EMPLOYEES
                    WHERE DEPARTMENT_ID = E.DEPARTMENT_ID);
  
  DBMS_OUTPUT.PUT_LINE('Averages after update');
  
  
  PRINT_AVERAGES();

  ROLLBACK;
END list_employees;
/




DECLARE

BEGIN
  
  list_employees(100);
  
END;
/
